### PR TITLE
Upgrade any-observable@0.3.0

### PR DESCRIPTION
**Pull request by SamVerschueren**
This is necessary in order to be able to use RxJS@6 with `stream-to-observable`. One downside is that `any-observable@0.3.0` required Node.js 6. So probably the tests will start failing. I can ES2016ify the codebase in a separate PR if you want.

// @sindresorhus

### CODE REVIEW

**Comment by jamestalmage** [comment]
We can drop Node 0.12 support.

**Comment by sindresorhus** [comment]
> any-observable@0.3.0 required Node.js 6

@jamestalmage Are you ok with dropping support for Node.js 4 too? Node.js 4 is officially unsupported by the Node.js core team. It's time.

**Comment by SamVerschueren** [comment]
Rebased on top of master.

**Comment by SamVerschueren** [comment]
@sindresorhus It doesn't fail on Node.js 4 though. But I assume that because `any-observable` doesn't support it officially, it could just publish a change as patch `0.3.1` that only works in Node.js 6.

**Comment by sindresorhus** [comment]
> But I assume that because any-observable doesn't support it officially, it could just publish a change as patch 0.3.1 that only works in Node.js 6.

Correct

**Comment by SamVerschueren** [comment]
Ping @jamestalmage 

Sorry to bother you but I need this one to fix listr.

**Comment by spalger** [comment]
Ping, sorry for being a nuisance

**Comment by jotatoledo** [comment]
Ping, sorry for bothering but the pr seems good to go if the merge conflicts are solved.

**Comment by sindresorhus** [comment]
Use @SamVerschueren's fork in the meantime: https://github.com/SamVerschueren/stream-to-observable

**Comment by jamestalmage** [comment]
@SamVerschueren and @sindresorhus 

You've got push access here, and publish access on npm. 

Fix, merge, and publish at will.

**Pull request closed without merging**
